# Site settings
course_name: Veri Yapıları ve Algoritmaları
Ders Tanımı: "Algoritma geliştirirken probleme özgü veri yapılarının seçimi ve kullanımı öğrenilemektedir."
#course_description: "Algoritma geliştirirken probleme özgü veri yapılarının seçimi ve kullanımı öğrenilemektedir."
course_semester: "Güz 2021"

baseurl: "/GUZ2021" # the subpath of your site, e.g. /blog/
url: "https://veri-yapilari-ve-algoritmalar.github.io/" # the base hostname & protocol for your site

schoolname: "Kocaeli Üniversitesi"
schoolurl: "https://kocaeli.edu.tr"

address: |
    Kocaeli

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
